apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python

spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
        logging: "true"
    spec:
      containers:
      - name: hello-python
        image: hello-k8s:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: hello_api
      #serviceAccountName: hello-python-sa    ## 與GSA綁定權限控制存取

      #   volumeMounts:           ## Mount secret
      #   - name: gcp-service-account-credentials-volume
      #     mountPath: /etc/gcp
      #     readOnly: true
      #   env:
      #   - name: GOOGLE_APPLICATION_CREDENTIALS
      #     value: /etc/gcp/dev-ml-awoo-com-tw-arangodb-access.json
      # volumes:
      # - name: gcp-service-account-credentials-volume
      #   secret:
      #     secretName: service-account-credentials-volume
